# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x0fmoaje.grpc.auth\"]\n\x1aValidateAccessTokenRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x7f\n\x1bValidateAccessTokenResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x12\n\nexpires_at\x18\x04 \x01(\x03\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"U\n\x17\x43heckMfaRequiredRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"^\n\x18\x43heckMfaRequiredResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x17\n\x0fis_mfa_required\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"_\n\x1bValidateAccountTokenRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x15\n\raccount_token\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x7f\n\x1cValidateAccountTokenResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08is_valid\x18\x02 \x01(\x08\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x32\xdd\x02\n\x0b\x41uthService\x12p\n\x13ValidateAccessToken\x12+.moaje.grpc.auth.ValidateAccessTokenRequest\x1a,.moaje.grpc.auth.ValidateAccessTokenResponse\x12g\n\x10\x43heckMfaRequired\x12(.moaje.grpc.auth.CheckMfaRequiredRequest\x1a).moaje.grpc.auth.CheckMfaRequiredResponse\x12s\n\x14ValidateAccountToken\x12,.moaje.grpc.auth.ValidateAccountTokenRequest\x1a-.moaje.grpc.auth.ValidateAccountTokenResponseB\x17\n\x13\x63om.moaje.grpc.authP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.moaje.grpc.authP\001'
  _globals['_VALIDATEACCESSTOKENREQUEST']._serialized_start=39
  _globals['_VALIDATEACCESSTOKENREQUEST']._serialized_end=132
  _globals['_VALIDATEACCESSTOKENRESPONSE']._serialized_start=134
  _globals['_VALIDATEACCESSTOKENRESPONSE']._serialized_end=261
  _globals['_CHECKMFAREQUIREDREQUEST']._serialized_start=263
  _globals['_CHECKMFAREQUIREDREQUEST']._serialized_end=348
  _globals['_CHECKMFAREQUIREDRESPONSE']._serialized_start=350
  _globals['_CHECKMFAREQUIREDRESPONSE']._serialized_end=444
  _globals['_VALIDATEACCOUNTTOKENREQUEST']._serialized_start=446
  _globals['_VALIDATEACCOUNTTOKENREQUEST']._serialized_end=541
  _globals['_VALIDATEACCOUNTTOKENRESPONSE']._serialized_start=543
  _globals['_VALIDATEACCOUNTTOKENRESPONSE']._serialized_end=670
  _globals['_AUTHSERVICE']._serialized_start=673
  _globals['_AUTHSERVICE']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
